-- FastAPI is the only trusted writer: React never talks to PostgreSQL directly,
-- and Row Level Security is not the authorisation layer until authentication lands.

-- Sequence gaps are expected because PostgreSQL sequences are not rolled back.
create sequence if not exists order_id_sequence start 1;
create sequence if not exists order_reference_sequence start 1;

create table orders (
    order_id     text primary key,
    order_number bigint not null unique,
    reference    text not null unique,
    status       text not null,
    created_at   timestamptz not null default now(),

    constraint orders_order_id_not_blank
        check (length(btrim(order_id)) > 0),
    constraint orders_reference_not_blank
        check (length(btrim(reference)) > 0),
    constraint orders_status_is_a_lifecycle_state
        check (status in ('DRAFT', 'AWAITING_OPTIMISATION', 'OPTIMISED', 'FINAL'))
);

create index orders_newest_first_idx on orders (created_at desc, order_number desc);

create table order_items (
    id             bigint generated by default as identity primary key,
    order_id       text not null references orders (order_id) on delete cascade,
    position       integer not null,

    item_code      text not null,
    item_reference text not null,

    width          integer not null,
    length         integer not null,
    depth          integer not null,

    weight         numeric not null,

    box_group      text,

    quantity       integer not null default 1,
    hazardous      boolean not null default false,

    constraint order_items_position_is_unique_per_order
        unique (order_id, position),
    constraint order_items_position_is_zero_based
        check (position >= 0),
    constraint order_items_item_code_is_canonical
        check (item_code ~ '^ITM-[0-9]{3,}$'),
    constraint order_items_item_reference_not_blank
        check (length(btrim(item_reference)) > 0),
    constraint order_items_dimensions_are_positive
        check (width > 0 and length > 0 and depth > 0),
    constraint order_items_weight_within_limits
        check (weight > 0 and weight <= 32),
    constraint order_items_box_group_not_blank
        check (box_group is null or length(btrim(box_group)) > 0),
    constraint order_items_quantity_is_at_least_one
        check (quantity >= 1)
);

create index order_items_order_id_idx on order_items (order_id, position);

-- Active = true with MaximumBoxes = 0 stays visible in Box Inventory but is
-- ineligible for optimisation. Solver eligibility is active AND maximum_boxes > 0.
create table box_types (
    reference     text primary key,
    -- Existing references retain their listing position across imports.
    sort_key      bigint generated by default as identity,

    width         numeric not null,
    length        numeric not null,
    depth         numeric not null,

    max_weight    numeric,
    box_weight    numeric,

    active        boolean not null default true,
    maximum_boxes integer not null default 0,

    constraint box_types_reference_not_blank
        check (length(btrim(reference)) > 0),
    constraint box_types_dimensions_are_positive
        check (width > 0 and length > 0 and depth > 0),
    constraint box_types_max_weight_is_positive
        check (max_weight is null or max_weight > 0),
    constraint box_types_box_weight_is_positive
        check (box_weight is null or box_weight > 0),
    constraint box_types_stock_is_never_negative
        check (maximum_boxes >= 0)
);

create index box_types_sort_key_idx on box_types (sort_key);

create table solutions (
    order_id      text primary key references orders (order_id) on delete cascade,
    solution_json jsonb not null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),

    constraint solutions_document_is_an_object
        check (jsonb_typeof(solution_json) = 'object')
);
